---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: urlstub-web-secrets
  namespace: urlstub
spec:
  encryptedData:
    MONGODB_URI: AgAYfTLnRBnYB3MjbIn1SohqFT3NYJbXyjBEG+8hJaBzWJtFzHHmz98DQM+Cnclx94fl74jQ/IXbRCkXcjXVk7xfSsCTcxU7mvw20/Z2QPbunVI4rQTYxUZYRfeJCM00Xxofkm441aP7jX6ET6NK14NBx03N19v/gsar6dcGXNijdzSSRlfVvKCSVsHUR9fC/m5GqfVdVAPPWecOq49kuawduva90t81yQP53vC5gvkFnIKdmDtE5TZBQLiufCxXVCdjRyDvq7u/WPlyE8/nskFTGpumJMpuim0+WxphoUFMmzdrgassnFpICe6nQ1KorXiadISj6KBMggIoKQNxdbMCBPWyWPf7gGjZ/SP8tK5/K8L3YXj+g7OsXL43j/uWd1Ku07BTEcKq+f69BT8tkcV7WAEkhCud82MIFdXcOp2nT6R3vxS7BGUNGw+6/Rz3t1a+NsuuTuYpgn9qKadPnXES9rghmoj7tyx9hqnsvMqVTByqK9cmSWw1dV4xtRJDDXbAnU6eZOWXAQrp7545VfhEefG7UQXYQTnriey9GfMrA5f+5jKAF1E0UkwKuRpwFS/MLGikEiOGqRFfT+l/AEKqTj8Or0GR+9WOCBEQjBb0rLv19KXOZn0chyV1QjL379JbjWW1dwRoOo3BACjxVFIEVqB/GrHLHiNP2VhtkRI345cNr0Ksaz9iRLZrhHFhHItkxNNIHlOtodkK8nVNl2UErl/BQjwGklyhuKgzzrcI6S+EcdqhuAKdmQ9HAob0Co+ClW3akeL9/vc5FyDbHmw+Y0qWHd8JSjOBK8VKNBHQcAjiS94402C+p40sr8fewbI1VWHfkq+2kYrGpw==
  template:
    metadata:
      creationTimestamp: null
      name: urlstub-web-secrets
      namespace: urlstub
    type: Opaque
