apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: urlstub-cert
  namespace: urlstub
spec:
  secretName: urlstub-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: s.liem.zip
  dnsNames:
  - dash.liem.zip