apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlstub-web
  namespace: urlstub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urlstub-web
  template:
    metadata:
      labels:
        app: urlstub-web
    spec:
      containers:
      - name: urlstub-web
        image: ghcr.io/liemeldert/urlstub:latest
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: urlstub-web-secrets
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
      imagePullSecrets:
      - name: dockerconfigjson-github-com
