name: Build and Push Stable Docker Image

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./urlstub-web
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/urlstub:stable
            ghcr.io/${{ github.repository_owner }}/urlstub:${{ github.ref_name }}